name: Sync to Hugging Face hub
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #allow manually trigger
  workflow_dispatch:


jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: git remote add space https://RamziRebai:$HF_TOKEN@https://huggingface.co/spaces/RamziRebai/hf_sum
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://RamziRebai:$HF_TOKEN@huggingface.co/spaces/RamziRebai/hf_sum main
